# docker-compose.yml

services:
  # 서비스 명
  db:
    # 사용할 이미지
    image: postgres
    # 컨테이너 실행 시 재시작
    restart: always
    # 컨테이너명 설정
    container_name: film_db
    # 환경 변수 설정
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    # 접근 포트 설정 (컨테이너 외부:컨테이너 내부)
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build: .
    container_name: film_api
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./app:/code/app
      - ./scheduler:/code/scheduler
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

  scheduler:
    build: .
    container_name: youtube_scheduler
    command: sh -c "sleep 10 && while true; do python -m scheduler.update_views; sleep 600; done"
    volumes:
      - ./app:/code/app
      - ./scheduler:/code/scheduler
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
